# Generated by Django 5.2.13 on 2026-05-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlog',
            name='device',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='searchlog',
            name='region',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='searchlog',
            name='session_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
