# Generated by Django 4.2.7 on 2026-03-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
