# Generated by Django 4.2.7 on 2026-04-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactionlog',
            name='device',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='interactionlog',
            name='region',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='interactionlog',
            name='session_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='interactionlog',
            name='action_type',
            field=models.CharField(choices=[('search', 'Search'), ('click', 'Click/View'), ('view', 'View'), ('add_to_cart', 'Add to Cart'), ('purchase', 'Purchase'), ('chat', 'Chat'), ('remove_from_cart', 'Remove from Cart')], max_length=20),
        ),
    ]
