# Generated by Django 4.2.7 on 2026-04-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(db_index=True, unique=True)),
                ('user_id', models.IntegerField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('preparing', 'Đang chuẩn bị hàng'), ('prepared', 'Chuẩn bị xong, chờ lấy hàng'), ('picked_up', 'Đã lấy hàng'), ('in_transit', 'Đang vận chuyển'), ('delivered', 'Đã giao hàng'), ('failed', 'Giao thất bại'), ('returned', 'Hoàn hàng')], default='pending', max_length=20)),
                ('method', models.CharField(choices=[('cod', 'Thanh toán khi nhận (COD)'), ('online', 'Đã thanh toán online')], default='cod', max_length=10)),
                ('receiver_name', models.CharField(blank=True, max_length=200)),
                ('receiver_phone', models.CharField(blank=True, max_length=20)),
                ('receiver_address', models.TextField(blank=True)),
                ('shipper_name', models.CharField(blank=True, max_length=200)),
                ('shipper_phone', models.CharField(blank=True, max_length=20)),
                ('tracking_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('estimated_date', models.DateField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
