# Generated by Django 4.2.7 on 2026-03-31 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('size', models.JSONField(default=list, help_text="Các kích thước có sẵn (ví dụ: ['S', 'M', 'L'])")),
                ('color', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
