# Generated by Django 4.2.7 on 2026-04-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(db_index=True)),
                ('user_id', models.IntegerField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('vnpay', 'VNPay')], default='vnpay', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('success', 'Thanh toán thành công'), ('failed', 'Thanh toán thất bại'), ('refunded', 'Đã hoàn tiền')], default='pending', max_length=10)),
                ('vnpay_txn_ref', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('vnpay_response_code', models.CharField(blank=True, max_length=10, null=True)),
                ('shipping_info', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
