# Generated by Django 4.2.7 on 2026-06-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('vnpay', 'VNPay'), ('cod', 'Thanh toán khi nhận hàng')], default='vnpay', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ thanh toán'), ('success', 'Thanh toán thành công'), ('failed', 'Thanh toán thất bại'), ('refunded', 'Đã hoàn tiền'), ('cod_pending', 'COD - Chờ thu tiền'), ('cod_collected', 'COD - Đã thu tiền')], default='pending', max_length=15),
        ),
    ]
