# Generated by Django 4.2.7 on 2026-04-20 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên danh mục', max_length=100)),
                ('slug', models.SlugField(help_text='Slug cho URL (ví dụ: laptop, dien-thoai)', unique=True)),
                ('description', models.TextField(blank=True, help_text='Mô tả danh mục', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên sản phẩm', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Giá sản phẩm', max_digits=12)),
                ('stock', models.IntegerField(default=0, help_text='Số lượng tồn kho')),
                ('description', models.TextField(blank=True, help_text='Mô tả sản phẩm', null=True)),
                ('specific_attributes', models.JSONField(blank=True, default=dict, help_text='Cấu hình riêng của sản phẩm dạng JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog', models.ForeignKey(help_text='Danh mục mà sản phẩm này thuộc về', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.catalog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
