# Generated by Django 4.2.7 on 2026-04-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Link ảnh sản phẩm', max_length=500, null=True),
        ),
    ]
