# Generated by Django 4.2.7 on 2026-06-02 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('author', models.CharField(help_text='Tác giả', max_length=255)),
                ('isbn', models.CharField(help_text='Mã ISBN', max_length=20, unique=True)),
                ('publisher', models.CharField(help_text='Nhà xuất bản', max_length=255)),
                ('pages', models.IntegerField(blank=True, help_text='Số trang', null=True)),
                ('language', models.CharField(blank=True, default='Tiếng Việt', help_text='Ngôn ngữ (VD: Tiếng Việt, English)', max_length=50)),
            ],
            options={
                'verbose_name': 'Sách',
                'verbose_name_plural': 'Sách',
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='ElectronicsProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('brand', models.CharField(help_text='Thương hiệu (VD: Apple, Samsung)', max_length=100)),
                ('warranty', models.IntegerField(default=12, help_text='Bảo hành (tháng)')),
                ('color', models.CharField(blank=True, default='', help_text='Màu sắc', max_length=50)),
            ],
            options={
                'verbose_name': 'Điện tử (chung)',
                'verbose_name_plural': 'Điện tử (chung)',
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='FashionProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('sizes', models.JSONField(default=list, help_text='Danh sách kích cỡ (VD: ["S","M","L","XL","XXL"])')),
                ('colors', models.JSONField(default=list, help_text='Danh sách màu sắc (VD: ["Đỏ","Đen","Trắng"])')),
                ('material', models.CharField(blank=True, default='', help_text='Chất liệu (VD: Cotton 100%, Polyester)', max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nữ'), ('unisex', 'Unisex')], default='unisex', help_text='Giới tính phù hợp', max_length=10)),
                ('fashion_type', models.CharField(blank=True, default='', help_text='Loại sản phẩm (VD: Áo thun, Quần jean, Giày sneaker)', max_length=50)),
            ],
            options={
                'verbose_name': 'Thời trang',
                'verbose_name_plural': 'Thời trang',
            },
            bases=('products.product',),
        ),
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name': 'Danh mục', 'verbose_name_plural': 'Danh mục'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sản phẩm (base)', 'verbose_name_plural': 'Sản phẩm (base)'},
        ),
        migrations.AlterField(
            model_name='catalog',
            name='slug',
            field=models.SlugField(help_text='Slug cho URL (ví dụ: sach, dien-tu)', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='catalog',
            field=models.ForeignKey(help_text='Danh mục sản phẩm', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.catalog'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Link ảnh', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Giá (VNĐ)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='specific_attributes',
            field=models.JSONField(blank=True, default=dict, help_text='[Legacy] Thuộc tính riêng dạng JSON (dành cho dữ liệu cũ)'),
        ),
        migrations.CreateModel(
            name='LaptopProduct',
            fields=[
                ('electronicsproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.electronicsproduct')),
                ('ram', models.CharField(help_text='RAM (VD: 8GB, 16GB DDR5)', max_length=50)),
                ('cpu', models.CharField(help_text='CPU (VD: Intel Core i7-1355U)', max_length=100)),
                ('storage', models.CharField(help_text='Bộ nhớ (VD: 512GB SSD NVMe)', max_length=50)),
                ('screen_size', models.CharField(help_text='Màn hình (VD: 15.6 inch Full HD)', max_length=50)),
                ('battery', models.CharField(blank=True, default='', help_text='Pin (VD: 56Wh, ~8 giờ)', max_length=50)),
                ('os', models.CharField(blank=True, default='', help_text='Hệ điều hành (VD: Windows 11 Home)', max_length=100)),
                ('weight', models.CharField(blank=True, default='', help_text='Khối lượng (VD: 1.8kg)', max_length=50)),
                ('graphics_card', models.CharField(blank=True, default='', help_text='Card đồ họa (VD: NVIDIA RTX 4060 8GB)', max_length=100)),
            ],
            options={
                'verbose_name': 'Laptop',
                'verbose_name_plural': 'Laptop',
            },
            bases=('products.electronicsproduct',),
        ),
        migrations.CreateModel(
            name='MobileProduct',
            fields=[
                ('electronicsproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.electronicsproduct')),
                ('ram', models.CharField(help_text='RAM (VD: 8GB, 12GB)', max_length=50)),
                ('storage', models.CharField(help_text='Bộ nhớ trong (VD: 128GB, 256GB)', max_length=50)),
                ('screen_size', models.CharField(help_text='Màn hình (VD: 6.7 inch AMOLED)', max_length=50)),
                ('battery', models.CharField(help_text='Pin (VD: 5000mAh)', max_length=50)),
                ('camera', models.CharField(blank=True, default='', help_text='Camera (VD: 50MP + 12MP + 10MP)', max_length=200)),
                ('os', models.CharField(blank=True, default='', help_text='HĐH (VD: Android 14, iOS 17)', max_length=100)),
                ('chip', models.CharField(blank=True, default='', help_text='Chip xử lý (VD: Snapdragon 8 Gen 3)', max_length=100)),
                ('sim', models.CharField(blank=True, default='', help_text='SIM (VD: Dual SIM nano)', max_length=50)),
            ],
            options={
                'verbose_name': 'Điện thoại di động',
                'verbose_name_plural': 'Điện thoại di động',
            },
            bases=('products.electronicsproduct',),
        ),
        migrations.CreateModel(
            name='RefrigeratorProduct',
            fields=[
                ('electronicsproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.electronicsproduct')),
                ('capacity', models.CharField(help_text='Dung tích (VD: 320L, 490L)', max_length=50)),
                ('energy_rating', models.CharField(blank=True, default='', help_text='Hiệu suất năng lượng (VD: 5 sao, Inverter)', max_length=50)),
                ('cooling_type', models.CharField(blank=True, default='', help_text='Công nghệ làm lạnh (VD: No Frost, Multi-Door)', max_length=100)),
                ('dimensions', models.CharField(blank=True, default='', help_text='Kích thước (VD: 60 x 63.5 x 185.5 cm)', max_length=100)),
                ('doors', models.IntegerField(blank=True, help_text='Số cánh tủ (VD: 2, 4)', null=True)),
                ('compressor', models.CharField(blank=True, default='', help_text='Máy nén (VD: Inverter Linear)', max_length=100)),
            ],
            options={
                'verbose_name': 'Tủ lạnh',
                'verbose_name_plural': 'Tủ lạnh',
            },
            bases=('products.electronicsproduct',),
        ),
        migrations.CreateModel(
            name='TVProduct',
            fields=[
                ('electronicsproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.electronicsproduct')),
                ('screen_size', models.CharField(help_text='Màn hình (VD: 55 inch, 65 inch)', max_length=50)),
                ('resolution', models.CharField(help_text='Độ phân giải (VD: 4K UHD, 8K)', max_length=50)),
                ('smart_tv', models.BooleanField(default=True, help_text='Có phải Smart TV không?')),
                ('panel_type', models.CharField(blank=True, default='', help_text='Tấm nền (VD: OLED, QLED, IPS, VA)', max_length=50)),
                ('refresh_rate', models.CharField(blank=True, default='', help_text='Tần số quét (VD: 60Hz, 120Hz)', max_length=50)),
                ('os', models.CharField(blank=True, default='', help_text='HĐH (VD: WebOS, Tizen, Android TV)', max_length=100)),
                ('hdr_support', models.CharField(blank=True, default='', help_text='HDR (VD: HDR10+, Dolby Vision)', max_length=100)),
            ],
            options={
                'verbose_name': 'Tivi',
                'verbose_name_plural': 'Tivi',
            },
            bases=('products.electronicsproduct',),
        ),
    ]
