# Generated by Django 4.2.7 on 2026-05-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
    ]
